music.playTone(330, music.beat(BeatFraction.Double))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Double))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Double))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Breve))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Breve))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Double))
music.playTone(392, music.beat(BeatFraction.Double))
music.playTone(392, music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Breve))
music.playTone(440, music.beat(BeatFraction.Double))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Breve))
music.playTone(523, music.beat(BeatFraction.Double))
music.playTone(494, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.playTone(659, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
basic.forever(function () {
    basic.showString("VISCA BARSA")
})
